# ===== APPLICATION CONFIGURATION

spring.application.name=unchk_backend

# === DATABASE CONFIGURATION

spring.datasource.url=jdbc:mysql://localhost:3306/unchk_management
spring.datasource.username=root
spring.datasource.password=

#==== JPA / HIBERNATE CONFIGURATION

# Automatically updates database tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

# MYSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
